name: Deploy Website

on:
  push:
    branches:
      - main   # change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholders in script.js
        run: |
          sed -i 's|PLACEHOLDER_SUPABASE_URL|${{ secrets.SUPABASE_URL }}|g' script.js
          sed -i 's|PLACEHOLDER_SUPABASE_ANON_KEY|${{ secrets.SUPABASE_ANON_KEY }}|g' script.js
          echo "Modified script.js - first 5 lines:"
          head -5 script.js

      - name: List all files
        run: |
          echo "All files to be deployed:"
          ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./
          force_orphan: true