name: Deploy Website

on:
  push:
    branches:
      - main   # change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create config.js from secrets
        run: |
          mkdir -p public
          echo "const SUPABASE_URL = \"${{ secrets.SUPABASE_URL }}\";" > public/config.js
          echo "const SUPABASE_ANON_KEY = \"${{ secrets.SUPABASE_ANON_KEY }}\";" >> public/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
